### ISSUE TITLE
Firefox 5

### ISSUE THREAD

**Issue by fischteichit** [georgepaterson/jquery-videobackground#1] opened 2011-07-03 02:05 UTC
Your Plugin is great, but there is a Problem with firefox 5. No Idea why. 
And you should disable fullscreen background video on Iphone (because the other links become somehow unclickable)

Greets

Leonid

**Comment by georgepaterson** [comment] 2011-07-03 11:14
Do you have an example URL of the plugin not working? I can't replicate on the demo page http://www.georgepaterson.com/sandbox/jquery-html5-video-background-demo/ using Firefox 5 on OSx.

iPhone support is a problem but i don't think there's value in encapsulating it in the plugin as there are a number of different methods of achieving this, for instance http://jquery-howto.blogspot.com/2010/09/iphone-ipod-detection-using-jquery.html

**Comment by georgepaterson** [comment] 2011-07-15 14:02
Closing as cannot reproduce.

**Closed as completed by georgepaterson** 2011-07-15 14:02 UTC
