### ISSUE TITLE
No video in Safari 5.1

### ISSUE THREAD

**Issue by rokitDev** [georgepaterson/jquery-videobackground#2] opened 2011-08-13 19:22 UTC
Hi George,

Fantastic plugin!   Works great in Firefox and Chrome.  It's not working in Safari Version 5.1 (6534.50) though.  Any ideas why not?

Thanks

**Comment by georgepaterson** [comment] 2011-08-14 17:02
Bug reproduced. I'll try and find a fix.

**Comment by georgepaterson** [comment] 2011-08-15 20:07
The problem was that i was calling a .m4v in the demo when it should have been a .mp4 which is supported in Safari. This issue should be fixed now.

**Comment by georgepaterson** [comment] 2011-08-21 18:51
Issue confirmed fixed.

**Closed as completed by georgepaterson** 2011-08-21 18:51 UTC
